In [2]:
import pandas as pd 
import numpy as np
import json
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

In [5]:
df=pd.read_csv('Qual Analysis - accounts_tidy.csv')

In [6]:
df.head(2)

,user_id,condition,user_finish_id,account,accountsOrder,justification,aor,num_messages,account_suspension,account_confidence,account_duration
0,e5188116-f79c-476a-b681-859c8c386e61,ai,67fb6d,1,13452,The person is advocating hate speech and viole...,1.00,2,Suspend,5.0,3.306
1,e5188116-f79c-476a-b681-859c8c386e61,ai,67fb6d,2,13452,Another account advocating actual IRL violence.,0.75,1,Suspend,5.0,3.887

In [8]:
df1=df[251:]

In [9]:
df1.head(2)

,user_id,condition,user_finish_id,account,accountsOrder,justification,aor,num_messages,account_suspension,account_confidence,account_duration
251,a69e967a-c238-4245-8091-e518ed2326f6,control,b23175,2,43512,More inflammatory remarks about someone's orie...,0.75,4,Suspend,3.76,10.693
252,a69e967a-c238-4245-8091-e518ed2326f6,control,b23175,3,43512,Any sort of derogatory slurs let's me know tha...,0.50,1,Suspend,5.00,20.891

In [14]:
len(df1)

1199

In [13]:
len(df)

1450